# Generated by Django 5.0.7 on 2024-08-08 15:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AccountInterest',
            fields=[
                ('ai_id', models.AutoField(primary_key=True, serialize=False)),
                ('ai_rate', models.FloatField()),
                ('ai_amount_period', models.IntegerField()),
            ],
            options={
                'db_table': 'account_interest',
            },
        ),
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('c_id', models.AutoField(primary_key=True, serialize=False)),
                ('c_name', models.CharField(max_length=100)),
                ('c_contact', models.CharField(max_length=13)),
                ('c_address', models.TextField()),
                ('c_email', models.EmailField(max_length=100)),
                ('c_password', models.CharField(max_length=50)),
                ('otp', models.CharField(blank=True, max_length=10, null=True)),
                ('otp_used', models.BooleanField(blank=True, default=False, null=True)),
            ],
            options={
                'db_table': 'customer',
            },
        ),
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('e_id', models.AutoField(primary_key=True, serialize=False)),
                ('e_name', models.CharField(max_length=100)),
                ('e_contact', models.CharField(max_length=13)),
                ('e_address', models.TextField()),
                ('e_email', models.EmailField(max_length=100)),
                ('e_password', models.CharField(max_length=50)),
                ('otp', models.CharField(blank=True, max_length=10, null=True)),
                ('otp_used', models.BooleanField(blank=True, default=False, null=True)),
            ],
            options={
                'db_table': 'employee',
            },
        ),
        migrations.CreateModel(
            name='TransactionType',
            fields=[
                ('tt_id', models.AutoField(primary_key=True, serialize=False)),
                ('tt_type', models.CharField(max_length=100)),
                ('tt_description', models.TextField()),
            ],
            options={
                'db_table': 'transaction_type',
            },
        ),
        migrations.CreateModel(
            name='Account',
            fields=[
                ('a_id', models.AutoField(primary_key=True, serialize=False)),
                ('a_open_date', models.DateField(auto_now_add=True)),
                ('a_balance', models.FloatField(default=0)),
                ('c_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='account_office_engine.customer')),
            ],
            options={
                'db_table': 'account',
            },
        ),
        migrations.CreateModel(
            name='Feedback',
            fields=[
                ('f_id', models.AutoField(primary_key=True, serialize=False)),
                ('f_description', models.TextField()),
                ('f_date', models.DateField(auto_now_add=True)),
                ('c_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='account_office_engine.customer')),
            ],
            options={
                'db_table': 'feedback',
            },
        ),
        migrations.CreateModel(
            name='InterestToCustomer',
            fields=[
                ('ic_id', models.AutoField(primary_key=True, serialize=False)),
                ('ic_amount_pay', models.FloatField()),
                ('ic_amount_added_date', models.DateField(auto_now_add=True)),
                ('a_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='account_office_engine.account')),
            ],
            options={
                'db_table': 'interest_to_customer',
            },
        ),
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('n_id', models.AutoField(primary_key=True, serialize=False)),
                ('n_description', models.TextField()),
                ('n_date', models.DateField(auto_now_add=True)),
                ('c_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='account_office_engine.customer')),
            ],
            options={
                'db_table': 'notification',
            },
        ),
        migrations.CreateModel(
            name='Transaction',
            fields=[
                ('t_id', models.AutoField(primary_key=True, serialize=False)),
                ('t_amount', models.FloatField()),
                ('t_date', models.DateField(auto_now_add=True)),
                ('a_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='source_account', to='account_office_engine.account')),
                ('transfer_account_no', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='destination_account', to='account_office_engine.account')),
                ('tt_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='account_office_engine.transactiontype')),
            ],
            options={
                'db_table': 'transaction',
            },
        ),
    ]
