# Generated by Django 5.0.7 on 2024-07-17 08:36

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('u_id', models.AutoField(primary_key=True, serialize=False)),
                ('u_name', models.CharField(max_length=100)),
                ('u_contact', models.CharField(max_length=13)),
                ('u_address', models.TextField()),
                ('u_email', models.EmailField(max_length=100)),
                ('u_password', models.CharField(max_length=50)),
            ],
            options={
                'db_table': 'user',
            },
        ),
    ]
