# Generated by Django 5.0.7 on 2024-08-02 03:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account_office_engine', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='account',
            name='a_balance',
            field=models.FloatField(default=0),
        ),
    ]
