# Generated by Django 5.0.7 on 2024-08-10 10:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account_office_engine', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Bank',
            fields=[
                ('b_id', models.AutoField(primary_key=True, serialize=False)),
                ('b_name', models.TextField()),
                ('b_city', models.TextField()),
                ('b_area', models.TextField()),
                ('b_branch', models.TextField()),
                ('b_address', models.TextField()),
                ('b_pincode', models.TextField()),
                ('b_ifsc', models.TextField()),
            ],
            options={
                'db_table': 'bank',
            },
        ),
    ]
