# Generated by Django 5.0.7 on 2024-08-02 07:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account_office_engine', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='transaction',
            name='transfer_account_no',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='destination_account', to='account_office_engine.account'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='transaction',
            name='a_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='source_account', to='account_office_engine.account'),
        ),
    ]
