# Generated by Django 5.0.7 on 2024-08-10 10:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account_office_engine', '0002_bank'),
    ]

    operations = [
        migrations.AddField(
            model_name='account',
            name='b_id',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='account_office_engine.bank'),
            preserve_default=False,
        ),
    ]
