# Generated by Django 5.0.7 on 2024-08-11 04:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account_office_engine', '0003_account_b_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bank',
            name='b_address',
            field=models.CharField(max_length=500),
        ),
        migrations.AlterField(
            model_name='bank',
            name='b_area',
            field=models.CharField(max_length=500),
        ),
        migrations.AlterField(
            model_name='bank',
            name='b_branch',
            field=models.CharField(max_length=500),
        ),
        migrations.AlterField(
            model_name='bank',
            name='b_city',
            field=models.CharField(max_length=500),
        ),
        migrations.AlterField(
            model_name='bank',
            name='b_ifsc',
            field=models.CharField(max_length=500),
        ),
        migrations.AlterField(
            model_name='bank',
            name='b_name',
            field=models.CharField(max_length=500),
        ),
        migrations.AlterField(
            model_name='bank',
            name='b_pincode',
            field=models.CharField(max_length=500),
        ),
    ]
